### ISSUE TITLE
Method `check_box_checked?' not defined error

### ISSUE THREAD

**Issue by AlexanderUlitin** [brainspec/enumerize#195]
Hello,

I've experienced error with loading gem code from bundle `gem 'enumerize', '~>0.11.0'`:

```
$ rake -T
rake aborted!
NameError: method `check_box_checked?' not defined in #<Class:0x0000000533c9d0>
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/enumerize-0.11.0/lib/enumerize/form_helper.rb:4:in `remove_method'
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/enumerize-0.11.0/lib/enumerize/form_helper.rb:4:in `block in <top (required)>'
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/enumerize-0.11.0/lib/enumerize/form_helper.rb:3:in `class_eval'
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/enumerize-0.11.0/lib/enumerize/form_helper.rb:3:in `<top (required)>'
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/enumerize-0.11.0/lib/enumerize.rb:58:in `<module:Enumerize>'
/home/alexander/.rvm/gems/ruby-2.2.1@ror_ecommerce/gems/enumerize-0.11.0/lib/enumerize.rb:4:in `<top (required)>'
/home/alexander/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `require'
/home/alexander/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/home/alexander/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `each'
/home/alexander/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `block in require'
/home/alexander/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `each'
/home/alexander/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `require'
/home/alexander/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.9.4/lib/bundler.rb:134:in `require'
```

I had no much time to investigate initial reasons of this error, but on other machine I've not experienced it.

This tiny fix helped me: https://github.com/brainspec/enumerize/pull/194

Thanks,
Alexander.

**Comment by nashby** [comment]
we decided to drop Rails 3 support and removed this backported method. can you please test master branch and see if it works?

**Comment by the-ult** [comment]
It seems to work, is there gonna be a new release soon? 
Since linking to the master branch is not my favorite best practice ;-)
