### ISSUE TITLE
Issue using enumerize 2.3.1

### ISSUE THREAD

**Issue by tcd** [brainspec/enumerize#352]
Using enumerize in a project I'm working on [(tcd/falsify)](https://github.com/tcd/falsify).
I'm trying to use version `2.3.1` but am getting the following output when running `rake test`:

```
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/predicatable.rb:15:in `method_missing': undefined method `underscore' for "web":Enumerize::Value (NoMethodError)
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/value.rb:20:in `initialize'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/attribute.rb:22:in `new'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/attribute.rb:22:in `block in initialize'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/attribute.rb:22:in `map'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/attribute.rb:22:in `initialize'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/base.rb:16:in `new'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/base.rb:16:in `enumerize'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/predicates.rb:40:in `enumerize'
	from /Users/clay/TCD/shopify/falsify/lib/falsify/models/product/product.rb:56:in `<class:Product>'
	from /Users/clay/TCD/shopify/falsify/lib/falsify/models/product/product.rb:9:in `<module:Falsify>'
	from /Users/clay/TCD/shopify/falsify/lib/falsify/models/product/product.rb:3:in `<top (required)>'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/clay/TCD/shopify/falsify/lib/falsify.rb:4:in `block in <top (required)>'
	from /Users/clay/TCD/shopify/falsify/lib/falsify.rb:4:in `each'
	from /Users/clay/TCD/shopify/falsify/lib/falsify.rb:4:in `<top (required)>'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/clay/TCD/shopify/falsify/test/test_helper.rb:13:in `<top (required)>'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/clay/TCD/shopify/falsify/test/falsify_test.rb:1:in `<top (required)>'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test:lib" -I"/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib" "/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/falsify_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

And here's the output of `rake test --trace`

```
** Invoke test (first_time)
** Execute test
Traceback (most recent call last):
        27: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
        26: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
        25: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
        24: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        23: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        22: from /Users/clay/TCD/shopify/falsify/test/falsify_test.rb:1:in `<top (required)>'
        21: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        20: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from /Users/clay/TCD/shopify/falsify/test/test_helper.rb:13:in `<top (required)>'
        18: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from /Users/clay/TCD/shopify/falsify/lib/falsify.rb:4:in `<top (required)>'
        15: from /Users/clay/TCD/shopify/falsify/lib/falsify.rb:4:in `each'
        14: from /Users/clay/TCD/shopify/falsify/lib/falsify.rb:4:in `block in <top (required)>'
        13: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        12: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from /Users/clay/TCD/shopify/falsify/lib/falsify/models/product/product.rb:3:in `<top (required)>'
        10: from /Users/clay/TCD/shopify/falsify/lib/falsify/models/product/product.rb:9:in `<module:Falsify>'
         9: from /Users/clay/TCD/shopify/falsify/lib/falsify/models/product/product.rb:56:in `<class:Product>'
         8: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/predicates.rb:40:in `enumerize'
         7: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/base.rb:16:in `enumerize'
         6: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/base.rb:16:in `new'
         5: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/attribute.rb:22:in `initialize'
         4: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/attribute.rb:22:in `map'
         3: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/attribute.rb:22:in `block in initialize'
         2: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/attribute.rb:22:in `new'
         1: from /Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/value.rb:20:in `initialize'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/enumerize-2.3.1/lib/enumerize/predicatable.rb:15:in `method_missing': undefined method `underscore' for "web":Enumerize::Value (NoMethodError)
rake aborted!
Command failed with status (1): [ruby -I"lib:test:lib" -I"/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib" "/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/falsify_test.rb" ]
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/testtask.rb:109:in `block (3 levels) in define'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/file_utils.rb:57:in `sh'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:34:in `sh'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/file_utils.rb:96:in `ruby'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:34:in `ruby'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/testtask.rb:105:in `block (2 levels) in define'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/file_utils_ext.rb:58:in `verbose'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/testtask.rb:101:in `block in define'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/clay/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/Users/clay/.rbenv/versions/2.6.4/bin/rake:23:in `load'
/Users/clay/.rbenv/versions/2.6.4/bin/rake:23:in `<main>'
Tasks: TOP => test
```

And here's the lockfile present when the problem occurs:

```
PATH
  remote: .
  specs:
    falsify (0.1.0)

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.0.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2)
    coderay (1.1.2)
    concurrent-ruby (1.1.5)
    docile (1.3.2)
    enumerize (2.3.1)
      activesupport (>= 3.2)
    i18n (1.7.0)
      concurrent-ruby (~> 1.0)
    json (2.2.0)
    method_source (0.9.2)
    minitest (5.13.0)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    rake (10.5.0)
    simplecov (0.17.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    thread_safe (0.3.6)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    zeitwerk (2.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  bundler (~> 2.0)
  enumerize (~> 2.3)
  falsify!
  minitest (~> 5.8)
  pry (~> 0.12.2)
  rake (~> 10.0)
  simplecov

BUNDLED WITH
   2.0.2
```

I don't seem to run into this issue when using `2.2.2`.

Also, these are the two files enumerize is being used in:
[product.rb](https://github.com/tcd/falsify/blob/master/lib/falsify/models/product/product.rb) and [product_variant.rb](https://github.com/tcd/falsify/blob/master/lib/falsify/models/product/product_variant.rb)

**Comment by nashby** [comment]
Hey @tcd. I just pushed a fix, could you please check master branch and report back if it fixes your issues? Thanks!

closed by #355
