### ISSUE TITLE
Enumerize::Value defines boolean methods in its singleton class, making it unmarshallable after ActiveRecord::Base#save is called

### ISSUE THREAD

**Issue by sluukkonen** [brainspec/enumerize#99]
I'm using enumerize in a Rails project. If I call any of the boolean methods in an enumerized field (like in a conditional validation), `Marshal.dump` (which Rails uses to serialize objects to the session) will fail after `save` is called.

I [set up a small rails project](https://github.com/sluukkonen/enumerize-test-app) to demonstrate this issue, but here are the important parts.

```ruby
class User < ActiveRecord::Base
  extend Enumerize
  enumerize :user_type,
    in: {normal: 0, admin: 1}
end
```

```ruby
$ rails console
Loading development environment (Rails 4.0.0)
irb(main):001:0> u = User.new(user_type: :normal)
=> #<User id: nil, user_type: 0, created_at: nil, updated_at: nil>
irb(main):002:0> u.user_type.normal?
=> true
irb(main):003:0> Marshal.dump(u)
=> "\x04\bo:\tUser\x16:\x10@attributes{\tI\"\aid\x06:\x06ET0I\"\x0Euser_type\x06;\aTi\x00I\"\x0Fcreated_at\x06;\aT0I\"\x0Fupdated_at\x06;\aT0:\x12@columns_hash{\tI\"\aid\x06;\aTo:4ActiveRecord::ConnectionAdapters::SQLite3Column\x0F:\n@nameI\"\aid\x06;\aT:\x0E@sql_typeI\"\fINTEGER\x06;\aT:\n@nullF:\v@limit0:\x0F@precision0:\v@scale0:\n@type:\finteger:\r@default0:\r@primaryT:\v@coder0I\"\x0Euser_type\x06;\aTo;\t\x0F;\nI\"\x0Euser_type\x06;\aT;\vI\"\finteger\x06;\aT;\fT;\r0;\x0E0;\x0F0;\x10;\x11;\x120;\x13F;\x140I\"\x0Fcreated_at\x06;\aTo:=ActiveRecord::AttributeMethods::TimeZoneConversion::Type\x06:\f@columno;\t\x0F;\nI\"\x0Fcreated_at\x06;\aT;\vI\"\rdatetime\x06;\aT;\fT;\r0;\x0E0;\x0F0;\x10:\rdatetime;\x120;\x13F;\x140I\"\x0Fupdated_at\x06;\aTo;\x15\x06;\x16o;\t\x0F;\nI\"\x0Fupdated_at\x06;\aT;\vI\"\rdatetime\x06;\aT;\fT;\r0;\x0E0;\x0F0;\x10;\x17;\x120;\x13F;\x140:\x17@aggregation_cache{\x00:\x17@association_cache{\x00:\x16@attributes_cache{\t\"\x0Euser_typei\x00I\"\aid\x06;\aT0I\"\x0Fcreated_at\x06;\aT0I\"\x0Fupdated_at\x06;\aT0:\x18@previously_changed{\x00:\x18@changed_attributes{\x06I\"\x0Euser_type\x06;\aT0:\x0E@readonlyF:\x0F@destroyedF:\x1C@marked_for_destructionF:\x1E@destroyed_by_association0:\x10@new_recordT:\t@txn0:\x1E@_start_transaction_state{\x00:\x17@transaction_state0:\x14@reflects_state[\x06F:'@_enumerized_values_for_validation{\x06:\x0Euser_typeI\"\vnormal\x06;\aF"
irb(main):004:0> u.save
   (0.1ms)  begin transaction
  SQL (3.0ms)  INSERT INTO "users" ("created_at", "updated_at", "user_type") VALUES (?, ?, ?)  [["created_at", Fri, 23 Aug 2013 14:38:08 UTC +00:00], ["updated_at", Fri, 23 Aug 2013 14:38:08 UTC +00:00], ["user_type", 0]]
   (1.8ms)  commit transaction
=> true
irb(main):005:0> Marshal.dump(u)
TypeError: singleton can't be dumped
	from (irb):5:in `dump'
	from (irb):5
	from /Users/sluukkonen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
	from /Users/sluukkonen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/sluukkonen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

I don't know the code base of enumerize well enough to tell why this happens only after `save`, but as far as I can see, the error itself happens because `Enumerize::Value` [defines](https://github.com/brainspec/enumerize/blob/master/lib/enumerize/value.rb#L25) the boolean methods in its singleton class.

**Comment by brennovich** [comment]
Any chance to have `predicatable` branch merged? As far as know it's working just fine :)

**Comment by lest** [comment]
@brennovich Version 0.10.1 has been released with the changes from the `predicatable` branch.

**Comment by brennovich** [comment]
@lest Thanks you so much :D
